UNDO_REDO_FILES = \
	objects/QCADUndoEntry.c                 objects/QCADUndoEntry.h \
	objects/QCADUndoEntryGroup.c            objects/QCADUndoEntryGroup.h \
	objects/QCADUndoEntryObjectState.c      objects/QCADUndoEntryObjectState.h \
	selection_undo.c                        selection_undo.h

STDIO_FILEIO_FILES = \
	fileio.c fileio.h

OBJECT_FILES = \
	objects/QCADCell.c                         objects/QCADCell.h \
	objects/QCADCompoundDO.c                   objects/QCADCompoundDO.h \
	objects/QCADObject.c                       objects/QCADObject.h \
	objects/QCADDesignObject.c                 objects/QCADDesignObject.h \
	objects/QCADDOContainer.c                  objects/QCADDOContainer.h \
	objects/QCADLabel.c                        objects/QCADLabel.h \
	objects/QCADLayer.c                        objects/QCADLayer.h \
	objects/QCADClockingLayer.c                objects/QCADClockingLayer.h \
	objects/QCADRuler.c                        objects/QCADRuler.h \
	objects/QCADStretchyObject.c               objects/QCADStretchyObject.h \
	objects/QCADElectrode.c                    objects/QCADElectrode.h \
	objects/QCADRectangleElectrode.c           objects/QCADRectangleElectrode.h \
	objects/QCADSubstrate.c                    objects/QCADSubstrate.h \
	objects/QCADParamSpecTypeList.c            objects/QCADParamSpecTypeList.h \
	objects/QCADPropertyUI.c                   objects/QCADPropertyUI.h \
	objects/QCADPropertyUISingle.c             objects/QCADPropertyUISingle.h \
	objects/QCADPropertyUIDouble.c             objects/QCADPropertyUIDouble.h \
	objects/QCADPropertyUINumeric.c            objects/QCADPropertyUINumeric.h \
	objects/QCADPropertyUIInt.c                objects/QCADPropertyInt.h \
	objects/QCADPropertyUIGroup.c              objects/QCADPropertyUIGroup.h \
	objects/QCADPropertyUIEnum.c               objects/QCADPropertyUIEnum.h \
	objects/QCADPropertyUIText.c               objects/QCADPropertyUIText.h \
	objects/QCADPropertyUIObjectList.c         objects/QCADPropertyUIObjectList.h \
	objects/QCADPropertyUIBoolean.c            objects/QCADPropertyUIBoolean.h \
	objects/QCADParamSpecObjectList.c          objects/QCADParamSpecObjectList.h
